personalweb/__init__.py
# Create the app
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

# App configuration

#app.config.from_object('config.DevelopmentConfig')

# Import views and blueprints

from personalweb.views import base

app.register_blueprint(base)

personalweb/views.py
# Import packages
from flask import render_template, Blueprint

# Create Blueprint and views
base = Blueprint('base', __name__)

@base.route('/')
@base.route('/home')
def home():
    return render_template('index.html')

@base.route('/portfolio')
def portfolio():
    return render_template('portfolio.html')

@base.route('/education')
def education():
    return render_template('education.html')

@base.route('/work')
def work():
    return render_template('work.html')

personalweb/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;900&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/styles/base.css">
    {% block style %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header class="header">
        <img class="logo" src="/static/logo.png">
        <div class="links">
            <a href="{{url_for('base.home')}}">HOME</a>
            <a href="{{url_for('base.portfolio')}}">PORTFOLIO</a>
            <a href="{{url_for('base.education')}}">EDUCATION</a>
            <a href="{{url_for('base.work')}}">WORK EXPERIENCE</a>
        </div>
    </header>
    <main>
        {% block content %}
        
        {% endblock %}
    </main>
    <footer>
        <div class="container">
            <div class="created-by">&#169; Created by V. Gardella</div>
            <div class="contact">
                <div class="phone"><b>Call:</b> <br> +11 111 1111</div>
                <div class="mail"><b>E-mail:</b> <br> v.gardella.ruiz@gmail.com</div>
            </div>
        </div>
    </footer>
</body>
</html>

personalweb/templates/education.html
{% extends 'base.html' %}

{% block style %} <link rel="stylesheet" href="/static/styles/education.css"> {% endblock %}

{% block title %} Victoria's Personal Website - Education{% endblock %}

{% block content %}
<section class="first">
    <div class="principal">
        <div class="container">
            <div class="title">Education</div>
            <div class="divider"><hr></div>
            <div class="subtext">These are the courses I have done!
            </div>
        </div>
    </div>
</section>

<section class="second">
    <div class="section-title">
        <h2>Degrees and certificates</h2>
        <hr>
    </div>
    <div class="education">
        <div class="certificate">
            <img src="./static/datascience-icon.jpg" alt="Data Science">
            <div class="text">
                <div class="title">Certification: Data Science</div>
                <div class="description">Completed: September, 2022</div>
            </div>
        </div>
        <div class="certificate">
            <img src="./static/dataanalytics-icon.png" alt="Data Analytics">
            <div class="text">
                <div class="title">Certification: Data Analytics</div>
                <div class="description">Complete: May, 2021</div>
            </div>
        </div>
        <div class="certificate">
            <img src="./static/geneng-icon.png" alt="PhD: Genetic Engineering">
            <div class="text">
                <div class="title">PhD: Biotechnology and Molecular Biology (Genetic Engineering)</div>
                <div class="description">Incomplete: 2019-2022</div>
            </div>
        </div>
        <div class="certificate">
            <img src="./static/biotech-icon.png" alt="Bachelors Degree: Biotechnology">
            <div class="text">
                <div class="title">Bachelor's Degree: Biotechnology and Molecular Biology</div>
                <div class="description">Complete: 2013-2018</div>
            </div>
        </div>
    </div>
</section>

<section class="third">
    <div class="section-title">
        <h2>Courses</h2>
        <hr>
    </div>
    <table class="courses">
        <thead>
            <tr>
                <th>Title</th>
                <th>Date</th>
                <th>Entity</th>
                <th>Topics</th>
                <th>Status</th>
                <th>Certificate</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="title">Python from Zero to Master with Python 3</td>
                <td class="date">December, 2022</td>
                <td class="entity">Udemy</td>
                <td class="topics">Python, HTML, CSS, Flask, Django</td>
                <td class="status">In Process</td>
                <td class="img"><a href="">Link</a></td>
            </tr>
            <tr>
                <td class="title">Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization</td>
                <td class="date">July, 2022</td>
                <td class="entity">Deeplearning.ai (Coursera)</td>
                <td class="topics">Machine Learning, Python</td>
                <td class="status">Complete</td>
                <td class="img"><a href="">Link</a></td>
            </tr>
            <tr>
                <td class="title">Introduction to Git and GitHub</td>
                <td class="date">July, 2022</td>
                <td class="entity">Google (Coursera)</td>
                <td class="topics">Git, GuitHub</td>
                <td class="status">Complete</td>
                <td class="img"><a href="">Link</a></td>
            </tr>
            <tr>
                <td class="title">ETL and Data Pipelines with Shell, Airflow and Kafka</td>
                <td class="date">July, 2022</td>
                <td class="entity">IBM (Coursera)</td>
                <td class="topics">ETL construction, Bash, Apache Airflow, Apache Kafka</td>
                <td class="status">Complete</td>
                <td class="img"><a href="">Link</a></td>
            </tr>
            <tr>
                <td class="title">Neural Networks and Deep Learning</td>
                <td class="date">June, 2022</td>
                <td class="entity">Deeplearning.ai (Coursera)</td>
                <td class="topics">Machine Learning, Python</td>
                <td class="status">Complete</td>
                <td class="img"><a href="">Link</a></td>
            </tr>
            <tr>
                <td class="title">Excel Basics for Data Analysis</td>
                <td class="date">June, 2022</td>
                <td class="entity">IBM (Coursera)</td>
                <td class="topics">Basic tasks (navigation, data entry, formulas), data manipulation (sorting, filtering), pivot tables</td>
                <td class="status">Complete</td>
                <td class="img"><a href="">Link</a></td>
            </tr>
            <tr>
                <td class="title">Probability and Statistics for Experimental Physics</td>
                <td class="date">Second semester, 2020</td>
                <td class="entity">UNLP (National University of La Plata)</td>
                <td class="topics">Probability, statistics, complex calculation with Python</td>
                <td class="status">Complete</td>
                <td class="img"><a href="">Link</a></td>
            </tr>
        </tbody>
    </table>
</section>
{% endblock %}

personalweb/templates/home.html
{% extends 'base.html' %}

{% block style %} 
<link rel="stylesheet" href="/static/styles/home.css">
{% endblock %}

{% block title %} Victoria's Personal Website - Homepage {% endblock %}

{% block content %}
<div class="principal">
    <div class="img-box">
        <img class="profile-pic" src="/static/profile-victoria.png" alt="My Photo">
        <div><hr></div>
        <div class="img-text">Come visit my personal profiles!</div>
        <div class="icons">
            <a href=""><img class="social" src="/static/insta-icon.png" alt="Instagram"></a>
            <a href="https://www.linkedin.com/in/victoria-macarena-gardella-ruiz-a8bab2234/"><img class="social" src="/static/linked-icon.png" alt="LinkedIn"></a>
            <a href="https://github.com/vicky-unlp"><img class="social" src="/static/github-icon.png" alt="GitHub"></a>
        </div>
    </div>
    <div class="text">
        <div class="title">Victoria Gardella</div>
        <div class="subtitle">Welcome to my personal Website!</div>
        <div class="subtext">This site was made using Flask not only as a project itself,
            but as a way to tell you a little bit about me and show my resume in an atractive format. I hope you enjoy my
            work!
        </div>
    </div>
</div>
<div class="introduction">
    <div class="container">
        <div class="text">
            <div class="title-container">
                <div class="title">About myself</div>
            </div>
            <div class="intro-divider"><hr></div>
            <div class="subtext">I'm an Argentinian programmer with knowledge in <strong>Python</strong>, both for 
                data analysis and app development, with knowledge of <strong>Flask and Django</strong>; <strong>HTML, CSS and JavaScript</strong>.
                <br><br>
                I have a Bachellor's Degree in Biotechnology and Molecular Biology, which gave me an extense knowledge in Mathematics,
                Statistics and a strong work ethic. I found my passion for programming shortly after and decided to pursue a career in development
                but still deciding between Back-End and Front-End.
            </div>
        </div>
        <div class="likes-dislikes">
            <div class="title-container">
                <div class="title">Likes and Dislikes</div>
            </div>
            <div class="intro-divider"><hr></div>
            <div class="imgs">
                <div class="cards1">
                    <div class="card">
                        <img src="/static/3792014_cat_halloween_kitty_icon.png" alt="">
                        <div class="like">Cats</div>
                    </div>
                    <div class="card">
                        <img src="/static/3994346_code_coding_css_html_programming_icon.png" alt="">
                        <div class="like">Coding</div>
                    </div>
                </div>
                <div class="cards2">
                    <div class="card">
                        <img src="/static/5404318_coffee_cup_glass_hot_icon.png" alt="">
                        <div class="like">Coffee</div>
                    </div>
                    <div class="card">
                        <img src="/static/5727018_cooking_food_kitchen_noodles_restaurant_icon.png" alt="">
                        <div class="like">Cooking</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="future">
    <div class="container">
        <div class="important">
            <img src="/static/8674977_ic_fluent_important_regular_icon.png" alt="Important! Looking for job">
        </div>
        <div class="expectations">
            <div class="title">Looking for Work!
            </div>
            <div class="subtext">I'm want to join an amazing team to further develope my programming skills and
                to share my habilities. If you like my work or have any recomendations/tips that you think can help
                me just let me know!</div>
        </div>
    </div>
</div>
{% endblock %}

personalweb/templates/index.html
{% extends 'base.html' %}

{% block style %} 
<link rel="stylesheet" href="/static/styles/index.css">
{% endblock %}

{% block title %} Victoria's Personal Website - Homepage {% endblock %}

{% block content %}
<section class="first">
    <div class="principal">
        <div class="img-box">
            <img class="profile-pic" src="/static/profile-victoria.png" alt="My Photo">
            <div><hr></div>
            <div class="img-text">Come visit my personal profiles!</div>
            <div class="icons">
                <a href=""><img class="social" src="/static/insta-icon.png" alt="Instagram"></a>
                <a href="https://www.linkedin.com/in/victoria-macarena-gardella-ruiz-a8bab2234/"><img class="social" src="/static/linked-icon.png" alt="LinkedIn"></a>
                <a href="https://github.com/vicky-unlp"><img class="social" src="/static/github-icon.png" alt="GitHub"></a>
            </div>
        </div>
        <div class="text">
            <div class="title">Victoria Gardella</div>
            <div class="subtitle">Welcome to my personal Website!</div>
            <div class="subtext">This site was made using Flask not only as a project itself,
                but as a way to tell you a little bit about me and show my resume in an atractive format. I hope you enjoy my
                work!
            </div>
        </div>
    </div>
</section>

<section class="second">
    <div class="introduction">
        <div class="container">
            <div class="text">
                <div class="title-container">
                    <div class="title">About myself</div>
                </div>
                <div class="intro-divider"><hr></div>
                <div class="subtext">I'm an Argentinian programmer with knowledge in <strong>Python</strong>, both for 
                    data analysis and app development, with knowledge of <strong>Flask and Django</strong>; <strong>HTML, CSS and JavaScript</strong>.
                    <br><br>
                    I have a Bachellor's Degree in Biotechnology and Molecular Biology, which gave me an extense knowledge in Mathematics,
                    Statistics and a strong work ethic. I found my passion for programming shortly after and decided to pursue a career in development
                    but still deciding between Back-End and Front-End.
                </div>
            </div>
            <div class="likes-dislikes">
                <div class="title-container">
                    <div class="title">Likes and Dislikes</div>
                </div>
                <div class="intro-divider"><hr></div>
                <div class="imgs">
                    <div class="cards1">
                        <div class="card">
                            <img src="/static/3792014_cat_halloween_kitty_icon.png" alt="">
                            <div class="like">Cats</div>
                        </div>
                        <div class="card">
                            <img src="/static/3994346_code_coding_css_html_programming_icon.png" alt="">
                            <div class="like">Coding</div>
                        </div>
                    </div>
                    <div class="cards2">
                        <div class="card">
                            <img src="/static/5404318_coffee_cup_glass_hot_icon.png" alt="">
                            <div class="like">Coffee</div>
                        </div>
                        <div class="card">
                            <img src="/static/5727018_cooking_food_kitchen_noodles_restaurant_icon.png" alt="">
                            <div class="like">Cooking</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="third">
    <div class="future">
        <div class="container">
            <div class="important">
                <img src="/static/8674977_ic_fluent_important_regular_icon.png" alt="Important! Looking for job">
            </div>
            <div class="expectations">
                <div class="title">Looking for Work!
                </div>
                <div class="subtext">I'm want to join an amazing team to further develope my programming skills and
                    to share my habilities. If you like my work or have any recomendations/tips that you think can help
                    me just let me know!</div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

personalweb/templates/portfolio.html
{% extends 'base.html' %}

{% block style %}
<link rel="stylesheet" href="/static/styles/portfolio.css"> {% endblock %}

{% block title %} Victoria's Personal Website - Portfolio {% endblock %}

{% block content %}
<section class="first">
    <div class="principal">
        <div class="container">
            <div class="title">My Projects</div>
            <div class="divider"><hr></div>
            <div class="subtext">Come and see the projects I have been working on!
            </div>
        </div>
    </div>
</section>

<section class="portfolio">
    <main class="posts">
        <div class="post">
            <img src="./static/projects/flask-web.png" alt="Website made with Flask">
            <h3>Personal Website - Flask</h3>
            <p>This personal website was made using Flask and the same HTML and CSS base code as the website one you are in rigth now.
            </p>
            <a class="post-btn" href="https://github.com/vicky-unlp/flask-personalweb.git">Go to the repository!</a>
        </div>
        <div class="post">
            <img src="./static/projects/landingpage.png" alt="Landing Page design">
            <h3>Basic landing page design</h3>
            <p>Template for landing page made using HTML y CSS. </p>
            <a class="post-btn" href="https://github.com/vicky-unlp/odin-landingpage.git">Go to the repository!</a>
        </div>
        <div class="post">
            <img src="./static/projects/recipepage.png" alt="Recipe website">
            <h3>Recipe page</h3>
            <p>Recipe page without style; HTML practice.</p>
            <a class="post-btn" href="https://github.com/vicky-unlp/odin-recipes.git">Go to the repository!</a>
        </div>
        <div class="post">
            <img src="./static/projects/gelt.png" alt="Technical excercise">
            <h3>Pipeline generation</h3>
            <p>Creation of pipeline for exctracting, cleaning and exporting data to a persistent database.
                Project made with Python and SQL Server.
            </p>
            <a class="post-btn" href="https://github.com/vicky-unlp/GELT_data.git">Go to the repository!</a>
        </div>
        <div class="post">
            <img src="./static/projects/science1.png" alt="Data Science Project">
            <h3>Market study - Bank of Portugal</h3>
            <p>Database analysis and training of machine learning algorithms; project made with Python. 
                Final project for Data Science certification course.</p>
            <a class="post-btn" href="https://github.com/vicky-unlp/data-science-project.git">Go to the repository!</a>
        </div>
        <div class="post">
            <img src="./static/projects/dash1.png" alt="Dashboard">
            <h3>Dashboard: air polution and contaminant identification</h3>
            <p>Air polution database analysis and dashboard creation. Final project for Dta Analysis
                certification course.
            </p>
            <a class="post-btn" href="https://github.com/vicky-unlp/data-analytics-project.git">Go to the repository!</a>
        </div>
    </main>
</section>
{% endblock %}

personalweb/templates/work.html
{% extends 'base.html' %}

{% block style %} <link rel="stylesheet" href="/static/styles/work.css"> {% endblock %}

{% block title %} Victoria's Personal Website - Work Experience{% endblock %}

{% block content %}

<section class="principal">
    <div class="banner">
        <div class="container">
            <div class="title">Work experience</div>
            <div class="divider"><hr></div>
            <div class="subtext">These are my previous jobs!
            </div>
        </div>
    </div>
</section>

<section class="work-experience">
    <div class="img">
        <img src="/static/aula3.jpg">
    </div>
    <div class="text">
        <div class="title">Assistant Professor</div>
        <div class="ubication">La Plata National University (Universidad Nacional de La Plata)</div>
        <hr>
        <div class="info">Description: 
            <ul>
                <li>Teaching tasks in the area of Basic Chemistry.</li>
                <li>Explanation of abstract theorical concepts.</li>
                <li>Team leading in complex laboratory tasks.</li>
            </ul>
        </div>
    </div>
</section>

<section class="message">
    <div class="container">
        <div class="img">
            <img src="" alt="Important Message">
        </div>
        <div class="text">
            <div class="title">Help me expand this page!</div>
            <div class="subtext">At the moment I'm looking for a full-time job: I'm intrested in programmer and
                developer positions, both as a junior or trainee. If you are interested in any of the
                projects I'm working on please let me know!</div>
        </div>
    </div>
</section>
{% endblock %}